MAX_WORK_LINES = 15
MAX_HELPER_COUNT = 3
PERCENT_SCALE = 100
CONSUMPTION_TAX_PERCENT = 10
ONE_HELPER_DEDUCTION_PERCENT = 35
MULTI_HELPER_DEDUCTION_PERCENT = 40
HELPER_FIELDS = ("temoto1", "temoto2", "temoto3")
