# Generated by Django 6.0.6 on 2026-08-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('general_contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.generalcontractor')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.site')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('worker_type', models.CharField(choices=[('職人', '職人'), ('手元', '手元')], max_length=10)),
                ('helper_percent', models.IntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_amount', models.IntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workapp.company')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workapp.worker')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_amount', models.IntegerField()),
                ('helper_count', models.IntegerField(default=0)),
                ('helpers', models.ManyToManyField(blank=True, related_name='helper_records', to='workapp.worker')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.site')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.worker')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.worktype')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.worker')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.worktype')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralContractorRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField()),
                ('general_contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.generalcontractor')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.worktype')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.company')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.worktype')),
            ],
        ),
    ]
