# Generated by Django 6.0.6 on 2026-08-11 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('moto', '元請'), ('shokunin', '職人'), ('temoto', '手元'), ('ouen', '応援')], max_length=50)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('temoto_percent', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='workrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workrecord',
            name='shokunin_deduction_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='temoto_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='voucher_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='helpers',
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='site',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='work_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='worker',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='helpers',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
