# Generated by Django 6.0.6 on 2026-08-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0002_unitmaster_workrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
