# Generated by Django 6.0.6 on 2026-08-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0003_workrecord_total_price_workrecord_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='work_size',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
