# Generated by Django 6.0.6 on 2026-08-15 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0004_workrecord_work_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyrate',
            options={'verbose_name': '応援企業単価', 'verbose_name_plural': '応援企業単価一覧'},
        ),
        migrations.AlterModelOptions(
            name='generalcontractor',
            options={'verbose_name': '元請', 'verbose_name_plural': '元請一覧'},
        ),
        migrations.AlterModelOptions(
            name='generalcontractorrate',
            options={'verbose_name': '元請単価', 'verbose_name_plural': '元請単価一覧'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': '現場', 'verbose_name_plural': '現場一覧'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': '作業員', 'verbose_name_plural': '作業員一覧'},
        ),
        migrations.AlterModelOptions(
            name='workerrate',
            options={'verbose_name': '作業員単価', 'verbose_name_plural': '作業員単価一覧'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': '作業種類', 'verbose_name_plural': '作業種類一覧'},
        ),
        migrations.RemoveField(
            model_name='companyrate',
            name='work_type',
        ),
        migrations.RemoveField(
            model_name='generalcontractorrate',
            name='work_type',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='helper_percent',
        ),
        migrations.RemoveField(
            model_name='workerrate',
            name='work_type',
        ),
        migrations.RemoveField(
            model_name='worktype',
            name='description',
        ),
        migrations.AddField(
            model_name='worker',
            name='temoto_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='手元％'),
        ),
        migrations.AlterField(
            model_name='companyrate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.company', verbose_name='応援企業'),
        ),
        migrations.AlterField(
            model_name='companyrate',
            name='unit_price',
            field=models.IntegerField(verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='generalcontractor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='元請名'),
        ),
        migrations.AlterField(
            model_name='generalcontractorrate',
            name='general_contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.generalcontractor', verbose_name='元請'),
        ),
        migrations.AlterField(
            model_name='generalcontractorrate',
            name='unit_price',
            field=models.IntegerField(verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='site',
            name='general_contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.generalcontractor', verbose_name='元請'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100, verbose_name='現場名'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workapp.company', verbose_name='所属企業'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=100, verbose_name='作業員名'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(choices=[('職人', '職人'), ('手元', '手元')], max_length=10, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='workerrate',
            name='unit_price',
            field=models.IntegerField(verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='workerrate',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.worker', verbose_name='作業員'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='作業種類名'),
        ),
    ]
