# Generated by Django 6.0.6 on 2026-08-16 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0005_alter_companyrate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='寸法')),
            ],
            options={
                'verbose_name': '寸法',
                'verbose_name_plural': '寸法一覧',
            },
        ),
        migrations.AddField(
            model_name='companyrate',
            name='work_size',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='workapp.worksize', verbose_name='寸法'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalcontractorrate',
            name='work_size',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='workapp.worksize', verbose_name='寸法'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerrate',
            name='work_size',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='workapp.worksize', verbose_name='寸法'),
            preserve_default=False,
        ),
    ]
