# Generated by Django 6.0.6 on 2026-08-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0006_worksize_companyrate_work_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '応援企業', 'verbose_name_plural': '応援企業一覧'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, verbose_name='応援企業名'),
        ),
    ]
