# Generated by Django 6.0.6 on 2026-08-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0007_alter_company_options_remove_company_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDefaultRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField()),
                ('work_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.worksize')),
            ],
            options={
                'verbose_name': '作業員共通単価',
                'verbose_name_plural': '作業員共通単価一覧',
            },
        ),
    ]
