# Generated by Django 6.0.6 on 2026-08-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0008_workerdefaultrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='general_contractor',
            field=models.CharField(default='', max_length=255),
        ),
    ]
