# Generated by Django 6.0.6 on 2026-08-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0009_workrecord_general_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
