# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0010_workrecord_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='temoto1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='手元1'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='temoto2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='手元2'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='temoto3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='手元3'),
        ),
    ]
