# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0011_workrecord_temoto1_temoto2_temoto3'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='dimension',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='寸法'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='work_size',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='work_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
