# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0012_workrecord_dimension_optional_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='備考'),
        ),
    ]
