# Generated by Django 6.0.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workapp", "0014_generalcontractor_closing_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintedDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("moto", "請求書（元請）"), ("shokunin", "支払書（職人）"), ("temoto", "支払書（手元）"), ("ouen", "支払書（応援）")], max_length=20, verbose_name="帳票種別")),
                ("party_name", models.CharField(max_length=255, verbose_name="相手名")),
                ("period_start", models.DateField(verbose_name="開始日")),
                ("period_end", models.DateField(verbose_name="終了日")),
                ("total_amount", models.IntegerField(default=0, verbose_name="合計（固定）")),
                ("status", models.CharField(choices=[("printed", "印刷済み"), ("cancelled", "取消")], default="printed", max_length=20, verbose_name="状態")),
                ("printed_at", models.DateTimeField(auto_now_add=True, verbose_name="印刷日時")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("party_company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="workapp.company", verbose_name="応援企業")),
                ("party_contractor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="workapp.generalcontractor", verbose_name="元請")),
                ("party_worker", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="workapp.worker", verbose_name="作業員")),
            ],
            options={
                "verbose_name": "印刷書類",
                "verbose_name_plural": "印刷書類一覧",
            },
        ),
        migrations.CreateModel(
            name="PrintedDocumentItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_total", models.IntegerField(blank=True, null=True, verbose_name="行金額（固定）")),
                ("snapshot", models.JSONField(blank=True, default=dict, verbose_name="印刷時点の内容")),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="workapp.printeddocument", verbose_name="印刷書類")),
                ("work_record", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="workapp.workrecord", verbose_name="作業記録")),
            ],
            options={
                "verbose_name": "印刷書類明細",
                "verbose_name_plural": "印刷書類明細",
            },
        ),
    ]
