# Generated by Django 6.0.6 on 2026-09-11

from django.db import migrations, models


def fill_billing_contractor(apps, schema_editor):
    WorkRecord = apps.get_model("workapp", "WorkRecord")
    for rec in WorkRecord.objects.all().iterator():
        if not rec.billing_contractor:
            rec.billing_contractor = rec.general_contractor or ""
            rec.save(update_fields=["billing_contractor"])


class Migration(migrations.Migration):

    dependencies = [
        ("workapp", "0015_printeddocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="workrecord",
            name="primary_company",
            field=models.CharField("1次企業", max_length=255, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workrecord",
            name="billing_contractor",
            field=models.CharField("請求先", max_length=255, default=""),
        ),
        migrations.RunPython(fill_billing_contractor, migrations.RunPython.noop),
    ]
