# Generated by Django 6.0.6 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workapp", "0016_workrecord_primary_and_billing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="worker_type",
            field=models.CharField(
                blank=True,
                choices=[("職人", "職人"), ("手元", "手元")],
                default="職人",
                max_length=10,
                verbose_name="種別",
            ),
        ),
        migrations.AlterField(
            model_name="printeddocument",
            name="kind",
            field=models.CharField(
                choices=[
                    ("moto", "請求書（元請）"),
                    ("worker", "支払書（作業員）"),
                    ("shokunin", "支払書（職人）"),
                    ("temoto", "支払書（手元）"),
                    ("ouen", "支払書（応援）"),
                ],
                max_length=20,
                verbose_name="帳票種別",
            ),
        ),
    ]
