# Generated by Django 6.0.6 on 2026-10-01 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0022_workrecord_size_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kagamisheet',
            options={'verbose_name': '支払書', 'verbose_name_plural': '支払書'},
        ),
        migrations.AlterField(
            model_name='generalcontractor',
            name='closing_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='毎月の締め日（1〜31）。未設定なら期間は手入力します。', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='締め日'),
        ),
        migrations.AlterField(
            model_name='kagamisheet',
            name='lines',
            field=models.JSONField(blank=True, default=list, verbose_name='支払書の行'),
        ),
        migrations.AlterField(
            model_name='kagamisheet',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='支払書の合計'),
        ),
        migrations.AlterField(
            model_name='printeddocument',
            name='kind',
            field=models.CharField(choices=[('moto', '請求書（元請）'), ('worker', '支払明細（作業員）'), ('shokunin', '支払明細（職人）'), ('temoto', '支払明細（手元）'), ('ouen', '支払明細（応援）')], max_length=20, verbose_name='帳票種別'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='general_contractor',
            field=models.CharField(default='', max_length=255, verbose_name='元請'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['voucher_no', 'date', 'site'], name='workrecord_search_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyrate',
            constraint=models.UniqueConstraint(fields=('company', 'work_size'), name='unique_company_rate'),
        ),
        migrations.AddConstraint(
            model_name='generalcontractorrate',
            constraint=models.UniqueConstraint(fields=('general_contractor', 'work_size'), name='unique_general_contractor_rate'),
        ),
        migrations.AddConstraint(
            model_name='workerdefaultrate',
            constraint=models.UniqueConstraint(fields=('work_size',), name='unique_worker_default_rate'),
        ),
    ]
