# Generated by Django 6.0.6 on 2026-10-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0024_party_kind_craftsman_affiliation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='site',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='worker',
        ),
        migrations.DeleteModel(
            name='UnitMaster',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
