# Generated by Django 6.0.6 on 2026-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0027_master_codes_and_record_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='billing_contractor',
            field=models.CharField(default='', help_text='印刷に出す請求先名です。', max_length=255, verbose_name='請求先'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='company',
            field=models.CharField(blank=True, default='', help_text='印刷に出す応援企業名です。', max_length=255),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='craftsman',
            field=models.CharField(blank=True, default='', help_text='印刷に出す職人名です。', max_length=255, verbose_name='職人'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='general_contractor',
            field=models.CharField(default='', help_text='印刷に出す元請名です。', max_length=255, verbose_name='元請'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='site',
            field=models.CharField(help_text='印刷に出す現場名です。マスタの名前を変えても、ここは変わりません。', max_length=255),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='temoto1',
            field=models.CharField(blank=True, default='', help_text='印刷に出す手元1の名前です。', max_length=100, verbose_name='手元1'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='temoto2',
            field=models.CharField(blank=True, default='', help_text='印刷に出す手元2の名前です。', max_length=100, verbose_name='手元2'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='temoto3',
            field=models.CharField(blank=True, default='', help_text='印刷に出す手元3の名前です。', max_length=100, verbose_name='手元3'),
        ),
    ]
